In [25]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_linnerud
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


# Example 01

In [27]:
X=np.array([[1,0],[1,1],[1,2],[1,3],[1,4]])
Y=np.array([1,4,3,8,9]).reshape(5,1)

In [28]:
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [29]:
Y

array([[1],
       [4],
       [3],
       [8],
       [9]])

# Estimated parameter vector

In [30]:
XTX_inv=np.linalg.inv(X.T.dot(X))
XTY=X.T.dot(Y)

In [31]:
XTX_inv

array([[ 0.6, -0.2],
       [-0.2,  0.1]])

In [32]:
XTY

array([[25],
       [70]])

In [33]:
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[1.],
       [2.]])

# Prediction vector

In [34]:
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [35]:
Y_Hat=X.dot(Beta_Hat)
Y_Hat

array([[1.],
       [3.],
       [5.],
       [7.],
       [9.]])

# Residual vector

In [36]:
Res_Hat=Y-Y_Hat
Res_Hat

array([[-2.22044605e-15],
       [ 1.00000000e+00],
       [-2.00000000e+00],
       [ 1.00000000e+00],
       [-1.77635684e-15]])

# Residual Sum of Squares

In [37]:
RSS=Res_Hat.T.dot(Res_Hat)
RSS

array([[6.]])

# Check with the Classical Linear Regression

In [38]:
X=np.array([0,1,2,3,4]).reshape(5,1)
Y=np.array([1,4,3,8,9]).reshape(5,1)

In [39]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

In [40]:
model.intercept_

array([1.])

In [41]:
model.coef_

array([[2.]])

# Example 02

In [42]:
X=np.array([[1,0],[1,1],[1,2],[1,3],[1,4]])
Y=np.array([[1,-1],[4,-1],[3,2],[8,3],[9,2]])

In [43]:
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [44]:
Y

array([[ 1, -1],
       [ 4, -1],
       [ 3,  2],
       [ 8,  3],
       [ 9,  2]])

# Estimated parameter matrix

In [45]:
XTX_inv=np.linalg.inv(X.T.dot(X))
XTY=X.T.dot(Y)

In [46]:
XTX_inv

array([[ 0.6, -0.2],
       [-0.2,  0.1]])

In [47]:
XTY

array([[25,  5],
       [70, 20]])

In [48]:
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[ 1., -1.],
       [ 2.,  1.]])

# Prediction matrix

In [49]:
Y_Hat=X.dot(Beta_Hat)
Y_Hat

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 3.00000000e+00,  2.22044605e-16],
       [ 5.00000000e+00,  1.00000000e+00],
       [ 7.00000000e+00,  2.00000000e+00],
       [ 9.00000000e+00,  3.00000000e+00]])

# Residual matrix

In [50]:
Res_Hat=Y-Y_Hat
Res_Hat

array([[-8.88178420e-16, -2.22044605e-16],
       [ 1.00000000e+00, -1.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00],
       [-3.55271368e-15, -1.00000000e+00]])

# Residual Sum of Squares

In [51]:
RSS=Res_Hat.T.dot(Res_Hat)
RSS

array([[ 6., -2.],
       [-2.,  4.]])

# Example 03

In [26]:
data=pd.read_csv("D:\\Workshops\\Machine Learning for Data Science & Artifcial Intelligence With Python\\data\\dataX.CSV")
data

X1  X2  X3   Y1   Y2
0    2   3   2  1.0  3.0
1   -1  -1   2  1.0  2.0
2   -2   0   3  2.0  4.0
3    4   1   1  2.0  1.0
4    1   1   2  3.0  5.0
5    4   2   4  4.0  6.0
6    5   3   5  1.0  3.0
7    3   1  -5  4.0  7.0
8    2   2  -2  5.0  8.0
9    3   7   6  2.0  2.0
10   2   3   2  NaN  NaN
11   1   2   3  NaN  NaN
12   1   4   2  NaN  NaN

In [27]:
data1=data[:10]
data1

X1  X2  X3   Y1   Y2
0   2   3   2  1.0  3.0
1  -1  -1   2  1.0  2.0
2  -2   0   3  2.0  4.0
3   4   1   1  2.0  1.0
4   1   1   2  3.0  5.0
5   4   2   4  4.0  6.0
6   5   3   5  1.0  3.0
7   3   1  -5  4.0  7.0
8   2   2  -2  5.0  8.0
9   3   7   6  2.0  2.0

In [28]:
data1["X0"]=1
data1.head()

<ipython-input-28-08d218f0bbcb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["X0"]=1


X1  X2  X3   Y1   Y2  X0
0   2   3   2  1.0  3.0   1
1  -1  -1   2  1.0  2.0   1
2  -2   0   3  2.0  4.0   1
3   4   1   1  2.0  1.0   1
4   1   1   2  3.0  5.0   1

In [39]:
X=data1[["X0","X1","X2","X3"]].values
Y=data1[["Y1","Y2"]].values

In [40]:
X

array([[ 1,  2,  3,  2],
       [ 1, -1, -1,  2],
       [ 1, -2,  0,  3],
       [ 1,  4,  1,  1],
       [ 1,  1,  1,  2],
       [ 1,  4,  2,  4],
       [ 1,  5,  3,  5],
       [ 1,  3,  1, -5],
       [ 1,  2,  2, -2],
       [ 1,  3,  7,  6]], dtype=int64)

In [41]:
Y

array([[1., 3.],
       [1., 2.],
       [2., 4.],
       [2., 1.],
       [3., 5.],
       [4., 6.],
       [1., 3.],
       [4., 7.],
       [5., 8.],
       [2., 2.]])

# Estimated parameter matrix

In [42]:
XTX_inv=np.linalg.inv(X.T.dot(X))
XTY=X.T.dot(Y)
Beta_Hat=XTX_inv.dot(XTY)
Beta_Hat

array([[ 2.6533429 ,  4.68234145],
       [ 0.06167254, -0.02426871],
       [ 0.12808385,  0.17301134],
       [-0.29234142, -0.47783262]])

# Prediction matrix

In [43]:
Y_Hat=X.dot(Beta_Hat)
Y_Hat

array([[2.5762567 , 4.19717282],
       [1.87890368, 3.57793359],
       [1.65297357, 3.29738102],
       [2.73577549, 4.28044534],
       [2.25841646, 3.87541885],
       [1.98683509, 3.01995884],
       [1.88425006, 2.69086885],
       [4.42815146, 7.17170974],
       [3.61753852, 5.93549194],
       [1.98089897, 2.95361901]])

# Residual matrix

In [44]:
Res_Hat=Y-Y_Hat
Res_Hat

array([[-1.5762567 , -1.19717282],
       [-0.87890368, -1.57793359],
       [ 0.34702643,  0.70261898],
       [-0.73577549, -3.28044534],
       [ 0.74158354,  1.12458115],
       [ 2.01316491,  2.98004116],
       [-0.88425006,  0.30913115],
       [-0.42815146, -0.17170974],
       [ 1.38246148,  2.06450806],
       [ 0.01910103, -0.95361901]])

# Residual Sum of Squares

In [45]:
RSS=Res_Hat.T.dot(Res_Hat)
RSS

array([[11.39840532, 15.40074343],
       [15.40074343, 30.62004938]])

# Predictions for new data

In [46]:
data2=data[10:]
data2

X1  X2  X3  Y1  Y2
10   2   3   2 NaN NaN
11   1   2   3 NaN NaN
12   1   4   2 NaN NaN

In [47]:
data2["X0"]=1

<ipython-input-47-567c721081a9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["X0"]=1


In [48]:
data2

X1  X2  X3  Y1  Y2  X0
10   2   3   2 NaN NaN   1
11   1   2   3 NaN NaN   1
12   1   4   2 NaN NaN   1

In [49]:
X_new=data2[["X0","X1","X2","X3"]].values

In [50]:
X_new

array([[1, 2, 3, 2],
       [1, 1, 2, 3],
       [1, 1, 4, 2]], dtype=int64)

In [51]:
Y_Hat_New=X_new.dot(Beta_Hat)
Y_Hat_New

array([[2.5762567 , 4.19717282],
       [2.09415889, 3.57059757],
       [2.64266801, 4.39445287]])

# Using Scikit Learn

In [52]:
model=MultiOutputRegressor(LinearRegression())
model.fit(X,Y)

MultiOutputRegressor(estimator=LinearRegression())

In [55]:
y_pred=model.predict(X_new)

In [56]:
y_pred

array([[2.5762567 , 4.19717282],
       [2.09415889, 3.57059757],
       [2.64266801, 4.39445287]])